### ISSUE TITLE
compose of janusgraph not working

### ISSUE THREAD

**Issue by mohamad-haddad-tribo** [invanalabs/docker-templates#3]
Cloned the latest commit,

docker-compose up -> The services are up and running even I could commit to janusgraph via console. 
But the UI is not reachable, even its logs and the engine logs are idle (running normal). Where should I debug? the browser results in timeouts

**Comment by mohamad-haddad-tribo** [comment]
It is network issue not related to the setup of dockers

**Comment by rrmerugu** [comment]
I'm glad you figured it out. :)
